/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import common.MessageBox;
import constant.Status;
import entity.Category;
import entity.Item;
import entity.Location;
import entity.Supplier;
import entity.Unit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Yanik
 */
public class ItemFormView extends javax.swing.JInternalFrame {
    List<Unit> units = new ArrayList<>();
    List<Supplier> suppliers = new ArrayList<>();
    List<Category> categories = new ArrayList<>();
    List<Location> locations = new ArrayList<>();


    /**
     * Creates new form ItemFormView
     */
    public ItemFormView() {
        initComponents();
    }
    
    public ItemFormView(Item item){
        initComponents();
      
    }
    
    public void setForm(Item item){
        this.textBoxItemCode.setText(item.getItemCode());
        this.textBoxItemName.setText(item.getItemName());
        this.textAreaDescription.setText(item.getDescription());
        this.textBoxUnitCost.setText(Double.toString(item.getUnitCost()));
        this.textBoxReorderLevel.setText(Double.toString(item.getReorderLevel()));
        this.textBoxQuantity.setText(Double.toString(item.getQuantity()));
        if(item.getCategory() != null){
           this.comboBoxCategory.setSelectedItem(item.getCategory().getName());
        }
        if(item.getLocation() != null){
           this.comboBoxLocation.setSelectedItem(item.getLocation().getName());
        }
        if(item.getUnit() != null){
          this.comboBoxUnit.setSelectedItem(item.getUnit().getName());  
        }
    }
    public boolean validateForm(){
        String errorMessage = "";
        int counter = 0;
        
        if(this.textBoxItemCode.getText().trim().equals("")){
            counter++;
            errorMessage += counter+". An item code is required\n";
        }
        if(this.textBoxItemName.getText().trim().equals("")){
            counter++;
            errorMessage += counter+". An item name is required\n";
        } 
        if(this.comboBoxCategory.getSelectedIndex() < 0){
            counter++;
            errorMessage += counter+". A category is required\n";
        }       
        if(this.comboBoxLocation.getSelectedIndex() < 0){
            counter++;
            errorMessage += counter+". A storage location is required\n";
        }
        if(this.comboBoxUnit.getSelectedIndex() < 0){
            counter++;
            errorMessage += counter+". A unit is required\n";
        }
        if(counter > 0){
            MessageBox.errorBox(this, "- Invalid Entries", errorMessage);
            return false;
        }
        return true;
    }
    
    
    public void setItem(){
        Item item = new Item();      
        
        Unit unit = this.units.get(this.comboBoxUnit.getSelectedIndex());        
        Supplier supplier = this.suppliers.get(this.comboBoxSupplier.getSelectedIndex());
        Location location = this.locations.get(this.comboBoxLocation.getSelectedIndex());
        Category category = this.categories.get(this.comboBoxCategory.getSelectedIndex());

        item.setUnit(unit);
        item.setLocation(location);
        item.setCategory(category);
        item.setItemCode(this.textBoxItemCode.getText().trim()); 
        item.setItemName(this.textBoxItemName.getText().trim());
        item.setDescription(this.textAreaDescription.getText().trim());
        item.setQuantity(Double.parseDouble(this.textBoxQuantity.getText()));
        item.setReorderLevel(Double.parseDouble(this.textBoxReorderLevel.getText())); 
        item.setUnitCost(Double.parseDouble(this.textBoxUnitCost.getText()));
        item.setStatus(Status.ACTIVE);
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelItemForm = new javax.swing.JPanel();
        textBoxItemCode = new javax.swing.JTextField();
        labelCategory = new javax.swing.JLabel();
        comboBoxCategory = new javax.swing.JComboBox<>();
        labelItemCode = new javax.swing.JLabel();
        textBoxItemName = new javax.swing.JTextField();
        labelItemName = new javax.swing.JLabel();
        comboBoxLocation = new javax.swing.JComboBox<>();
        labelLocation = new javax.swing.JLabel();
        scrollPaneItemTable = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();
        labelDescription = new javax.swing.JLabel();
        addStorageLocation = new javax.swing.JButton();
        buttonAddCategory = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListSupplier = new javax.swing.JList<>();
        comboBoxSupplier = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        buttonAddSupplier = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelReorderLevek = new javax.swing.JLabel();
        labelQuantity = new javax.swing.JLabel();
        labelUnitCost = new javax.swing.JLabel();
        comboBoxUnit = new javax.swing.JComboBox<>();
        labelUnit = new javax.swing.JLabel();
        buttonAddUnit = new javax.swing.JButton();
        textBoxUnitCost = new javax.swing.JTextField();
        textBoxReorderLevel = new javax.swing.JTextField();
        textBoxQuantity = new javax.swing.JTextField();
        buttonAction = new javax.swing.JButton();
        buttonClear = new javax.swing.JButton();
        buttonClear1 = new javax.swing.JButton();

        panelItemForm.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textBoxItemCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCategory.setText("Category");

        comboBoxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelItemCode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelItemCode.setText("Item Code");

        textBoxItemName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelItemName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelItemName.setText("Item Name");

        comboBoxLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelLocation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelLocation.setText("Storage Location");

        textAreaDescription.setColumns(20);
        textAreaDescription.setRows(5);
        scrollPaneItemTable.setViewportView(textAreaDescription);

        labelDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDescription.setText("Description");

        addStorageLocation.setText("jButton1");

        buttonAddCategory.setText("jButton1");
        buttonAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelItemFormLayout = new javax.swing.GroupLayout(panelItemForm);
        panelItemForm.setLayout(panelItemFormLayout);
        panelItemFormLayout.setHorizontalGroup(
            panelItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textBoxItemName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneItemTable, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelItemFormLayout.createSequentialGroup()
                            .addGroup(panelItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelItemFormLayout.createSequentialGroup()
                                    .addGroup(panelItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45))
                                .addGroup(panelItemFormLayout.createSequentialGroup()
                                    .addGroup(panelItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelItemFormLayout.createSequentialGroup()
                                            .addComponent(labelCategory)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(buttonAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)))
                            .addGroup(panelItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelItemFormLayout.createSequentialGroup()
                                    .addComponent(labelLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(addStorageLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                    .addComponent(textBoxItemCode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelItemFormLayout.setVerticalGroup(
            panelItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelItemCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBoxItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelItemName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textBoxItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneItemTable, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategory)
                    .addComponent(labelLocation)
                    .addComponent(addStorageLocation)
                    .addComponent(buttonAddCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelItemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Supplier(s)"));

        ListSupplier.setToolTipText("Right click for more options");
        jScrollPane1.setViewportView(ListSupplier);

        comboBoxSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Add");

        buttonAddSupplier.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(comboBoxSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(buttonAddSupplier)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelReorderLevek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelReorderLevek.setText("Re-Order Level");

        labelQuantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelQuantity.setText("Quantity");

        labelUnitCost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUnitCost.setText("Unit Cost");

        comboBoxUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelUnit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelUnit.setText("Unit");

        buttonAddUnit.setText("jButton1");

        textBoxUnitCost.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textBoxUnitCost.setText("0.00");

        textBoxReorderLevel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textBoxReorderLevel.setText("0");

        textBoxQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textBoxQuantity.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(textBoxUnitCost, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelUnitCost, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelReorderLevek, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(labelUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textBoxReorderLevel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textBoxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 110, Short.MAX_VALUE)
                                .addComponent(buttonAddUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(comboBoxUnit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUnitCost)
                    .addComponent(labelReorderLevek))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxUnitCost, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBoxReorderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantity)
                    .addComponent(labelUnit)
                    .addComponent(buttonAddUnit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBoxQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        buttonAction.setText("Add");
        buttonAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionActionPerformed(evt);
            }
        });

        buttonClear.setText("Clear");

        buttonClear1.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelItemForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAction, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelItemForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAction, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonClear1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionActionPerformed
        
    }//GEN-LAST:event_buttonActionActionPerformed

    private void buttonAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddCategoryActionPerformed
        JOptionPane.showInputDialog(this, "New Category", "New Category");
    }//GEN-LAST:event_buttonAddCategoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListSupplier;
    private javax.swing.JButton addStorageLocation;
    private javax.swing.JButton buttonAction;
    private javax.swing.JButton buttonAddCategory;
    private javax.swing.JButton buttonAddSupplier;
    private javax.swing.JButton buttonAddUnit;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonClear1;
    private javax.swing.JComboBox<String> comboBoxCategory;
    private javax.swing.JComboBox<String> comboBoxLocation;
    private javax.swing.JComboBox<String> comboBoxSupplier;
    private javax.swing.JComboBox<String> comboBoxUnit;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelItemCode;
    private javax.swing.JLabel labelItemName;
    private javax.swing.JLabel labelLocation;
    private javax.swing.JLabel labelQuantity;
    private javax.swing.JLabel labelReorderLevek;
    private javax.swing.JLabel labelUnit;
    private javax.swing.JLabel labelUnitCost;
    private javax.swing.JPanel panelItemForm;
    private javax.swing.JScrollPane scrollPaneItemTable;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JTextField textBoxItemCode;
    private javax.swing.JTextField textBoxItemName;
    private javax.swing.JTextField textBoxQuantity;
    private javax.swing.JTextField textBoxReorderLevel;
    private javax.swing.JTextField textBoxUnitCost;
    // End of variables declaration//GEN-END:variables
}
