/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;


import entity.Item;
import entity.Receivable;
import entity.Request;
import entity.Supplier;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import services.DatabaseService;
import services.ItemService;
import services.ReceivableService;
import services.RequestService;

/**
 *
 * @author Yanik
 */
public class TransactionInternalFrame extends javax.swing.JInternalFrame {
    
    private ItemService _dbService = null;
    private List<Supplier> suppliers = new ArrayList<>();
    private List<Request> _resquests = new ArrayList<>();
    private List<Receivable> _receivables = new ArrayList<>();
    /**
     * Creates new form ItemView
     */
    public TransactionInternalFrame() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.initRequest();;
        this.initReceivable();
      
    }

   
    public void initRequest(){
        ((DefaultTableModel) this.tableRequest.getModel()).setNumRows(0);
        RequestService requestService = new RequestService();
        DefaultTableModel model = (DefaultTableModel) this.tableRequest.getModel();
        model.setRowCount(0);
        this._resquests = requestService.findAll(Request.class);
        for(Request item : _resquests){ 
            model.addRow(new Object[]{
                                       item.getItem().getItemName(),
                                       item.getAmount(),
                                       item.getRequester().getUsername(),
                                       item.getDateRequested()
                                     });
        }
    }
    
    
    public void searchRequest(String search){
        ((DefaultTableModel) this.tableRequest.getModel()).setNumRows(0);
        RequestService requestService = new RequestService();
        DefaultTableModel model = (DefaultTableModel) this.tableRequest.getModel();
        model.setRowCount(0);
        this._resquests = requestService.search(search);
        for(Request item : _resquests){ 
            model.addRow(new Object[]{
                                       item.getItem().getItemName(),
                                       item.getAmount(),
                                       item.getRequester().getUsername(),
                                       item.getDateRequested()
                                     });
        }
    }
    
    
   public void initReceivable(){
        ((DefaultTableModel) this.tableReceivable.getModel()).setNumRows(0);
        ReceivableService receivableService = new ReceivableService();
        DefaultTableModel model = (DefaultTableModel) this.tableReceivable.getModel();
        model.setRowCount(0);
        this._receivables = receivableService.findAll(Receivable.class);
        for(Receivable item : this._receivables){ 
            model.addRow(new Object[]{
                                       item.getItem().getItemName(),
                                       item.getSupplier().getName(),
                                       item.getAmount(),
                                       item.getCost(),
                                       item.getDateReceived()
                                     });
        }
    }
   
    public void searchReceivable(String search){
        ((DefaultTableModel) this.tableReceivable.getModel()).setNumRows(0);
        ReceivableService receivableService = new ReceivableService();
        DefaultTableModel model = (DefaultTableModel) this.tableReceivable.getModel();
        model.setRowCount(0);
        this._receivables = receivableService.search(search);
        for(Receivable item : this._receivables){ 
            model.addRow(new Object[]{
                                       item.getItem().getItemName(),
                                       item.getSupplier().getName(),
                                       item.getAmount(),
                                       item.getCost(),
                                       item.getDateReceived()
                                     });
        }
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenuTableOption = new javax.swing.JPopupMenu();
        popupMenuOption = new javax.swing.JPopupMenu();
        menuItemRemove = new javax.swing.JMenuItem();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 0), new java.awt.Dimension(4, 32767));
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonClose = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRequest = new javax.swing.JTable();
        txtboxSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        buttonDelete = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableReceivable = new javax.swing.JTable();
        txtboxSearch2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        buttonDelete1 = new javax.swing.JButton();
        buttonEdit1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        menuItemRemove.setText("Remove");
        menuItemRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRemoveActionPerformed(evt);
            }
        });
        popupMenuOption.add(menuItemRemove);

        setClosable(true);

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(106, 106, 106));
        jLabel1.setText("Transactions");

        buttonClose.setText("Close");
        buttonClose.setBorder(null);
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel6.setBackground(new java.awt.Color(241, 241, 241));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1069, 594));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        tableRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ", "Amount", "Requester", "Date Requested"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRequest.setToolTipText("Right Click to view options");
        tableRequest.setGridColor(new java.awt.Color(255, 255, 255));
        tableRequest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableRequestFocusLost(evt);
            }
        });
        tableRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRequestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableRequest);
        if (tableRequest.getColumnModel().getColumnCount() > 0) {
            tableRequest.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        txtboxSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtboxSearch.setForeground(new java.awt.Color(153, 153, 153));
        txtboxSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtboxSearchKeyPressed(evt);
            }
        });

        buttonDelete.setText("Delete");

        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(106, 106, 106));
        jLabel3.setText("Search");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buttonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete)
                        .addGap(1056, 1056, 1056))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane2)
                            .addComponent(txtboxSearch))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtboxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDelete)
                    .addComponent(buttonEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Request", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMinimumSize(new java.awt.Dimension(1069, 594));

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        tableReceivable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ", "Supplier", "Amount", "Cost", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableReceivable.setToolTipText("Right Click to view options");
        tableReceivable.setGridColor(new java.awt.Color(255, 255, 255));
        tableReceivable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tableReceivableFocusLost(evt);
            }
        });
        tableReceivable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReceivableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableReceivable);
        if (tableReceivable.getColumnModel().getColumnCount() > 0) {
            tableReceivable.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableReceivable.getColumnModel().getColumn(4).setHeaderValue("Unit Cost");
        }

        txtboxSearch2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtboxSearch2.setForeground(new java.awt.Color(153, 153, 153));
        txtboxSearch2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtboxSearch2KeyPressed(evt);
            }
        });

        buttonDelete1.setText("Delete");
        buttonDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDelete1ActionPerformed(evt);
            }
        });

        buttonEdit1.setText("Edit");
        buttonEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEdit1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(106, 106, 106));
        jLabel2.setText("Search");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(buttonEdit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonDelete1)
                        .addGap(1056, 1056, 1056))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addComponent(jScrollPane3)
                            .addComponent(txtboxSearch2))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtboxSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDelete1)
                    .addComponent(buttonEdit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receivables", jPanel4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(683, 683, 683))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRemoveActionPerformed
       
    }//GEN-LAST:event_menuItemRemoveActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
       
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        
    }//GEN-LAST:event_buttonEditActionPerformed

    private void tableRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRequestMouseClicked
        
        
    }//GEN-LAST:event_tableRequestMouseClicked

    private void tableRequestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableRequestFocusLost
         
    }//GEN-LAST:event_tableRequestFocusLost

    private void txtboxSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtboxSearchKeyPressed
        this.searchRequest(this.txtboxSearch.getText().trim());
    }//GEN-LAST:event_txtboxSearchKeyPressed

    private void tableReceivableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableReceivableFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tableReceivableFocusLost

    private void tableReceivableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReceivableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableReceivableMouseClicked

    private void txtboxSearch2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtboxSearch2KeyPressed
        this.searchReceivable(this.txtboxSearch2.getText().trim());
    }//GEN-LAST:event_txtboxSearch2KeyPressed

    private void buttonEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEdit1ActionPerformed

    private void buttonDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDelete1ActionPerformed
       
    }//GEN-LAST:event_buttonDelete1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDelete1;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonEdit1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem menuItemRemove;
    private javax.swing.JPopupMenu popupMenuOption;
    private javax.swing.JPopupMenu popupMenuTableOption;
    private javax.swing.JTable tableReceivable;
    private javax.swing.JTable tableRequest;
    private javax.swing.JTextField txtboxSearch;
    private javax.swing.JTextField txtboxSearch2;
    // End of variables declaration//GEN-END:variables
}
